from setuptools import setup

setup(name='waabi',
    version='0.2.1',
    description='waabi is an Ojibwe Word for "s/he has vision, sees"',
    url='https://github.com/bdunford/waabi/',
    author='b1rch',
    author_email='birch.dunford@gmail.com',
    license='MIT',
    include_package_data=True,
    packages=[
        'waabi',
        'waabi/belch',
        'waabi/scan',
        'waabi/utility',
        'waabi/wordlists',
        'waabi/payloads',
        'waabi/target',
    ],
    package_data={
        "waabi/wordlists":["*.txt"],
        "waabi/belch":["*.pyt"],
        "waabi/payloads":[
            "*.xml",
            "*.sql",
            "*.ql",
            "*.xlsx",
            "*.xlsm",
            "*.xls",
            "*.doc",
            "*.docx",
            "*.svg",
            "*.html",
            "*.jpeg",
            "*.pdf",
            "*.gif",
            "*.bmp",
            "*.ico",
            "*.tiff",
            "*.png",
            "*.txt",
            "*.rtf",
            "*.json"
        ]
    },
    zip_safe=False,
    scripts=['bin/waabi'],
    install_requires=[
        'requests',
        'requests-html',
        'pyjwt',
        'cryptography'
    ]
)
